name = "ApproximationAnalysis"
uuid = "82321e43-16b0-4e95-943b-273a726d7f5d"
authors = ["Nick Timmons <ngtimmons@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"