name = "ApproximationAnalysis"
uuid = "fdfa7196-0679-42b3-9b39-852c8f23007b"
authors = ["Nick Timmons <ngtimmons@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"